# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attribute_based_clustering_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AttributeBasedClusteringDialog(object):
    def setupUi(self, AttributeBasedClusteringDialog):
        AttributeBasedClusteringDialog.setObjectName("AttributeBasedClusteringDialog")
        AttributeBasedClusteringDialog.resize(540, 515)
        self.gridLayout_2 = QtWidgets.QGridLayout(AttributeBasedClusteringDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(AttributeBasedClusteringDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.addFieldButton = QtWidgets.QPushButton(AttributeBasedClusteringDialog)
        self.addFieldButton.setObjectName("addFieldButton")
        self.gridLayout_2.addWidget(self.addFieldButton, 2, 1, 1, 2)
        self.deleteAllButton = QtWidgets.QPushButton(AttributeBasedClusteringDialog)
        self.deleteAllButton.setObjectName("deleteAllButton")
        self.gridLayout_2.addWidget(self.deleteAllButton, 4, 1, 1, 2)
        self.deleteSelectedButton = QtWidgets.QPushButton(AttributeBasedClusteringDialog)
        self.deleteSelectedButton.setObjectName("deleteSelectedButton")
        self.gridLayout_2.addWidget(self.deleteSelectedButton, 3, 1, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(AttributeBasedClusteringDialog)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 6, 0, 1, 3)
        self.runButton = QtWidgets.QPushButton(AttributeBasedClusteringDialog)
        self.runButton.setObjectName("runButton")
        self.gridLayout_2.addWidget(self.runButton, 6, 4, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(AttributeBasedClusteringDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout_2.addWidget(self.cancelButton, 6, 5, 1, 1)
        self.label = QtWidgets.QLabel(AttributeBasedClusteringDialog)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.fieldsComboBox = QgsFieldComboBox(AttributeBasedClusteringDialog)
        self.fieldsComboBox.setObjectName("fieldsComboBox")
        self.gridLayout_2.addWidget(self.fieldsComboBox, 1, 1, 1, 2)
        self.vectorLayerComboBox = QgsMapLayerComboBox(AttributeBasedClusteringDialog)
        self.vectorLayerComboBox.setObjectName("vectorLayerComboBox")
        self.gridLayout_2.addWidget(self.vectorLayerComboBox, 0, 1, 1, 2)
        self.settingsGroup = QtWidgets.QGroupBox(AttributeBasedClusteringDialog)
        self.settingsGroup.setObjectName("settingsGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.settingsGroup)
        self.gridLayout.setObjectName("gridLayout")
        self.linkageMethodComboBox = QtWidgets.QComboBox(self.settingsGroup)
        self.linkageMethodComboBox.setObjectName("linkageMethodComboBox")
        self.linkageMethodComboBox.addItem("")
        self.linkageMethodComboBox.addItem("")
        self.linkageMethodComboBox.addItem("")
        self.linkageMethodComboBox.addItem("")
        self.linkageMethodComboBox.addItem("")
        self.linkageMethodComboBox.addItem("")
        self.gridLayout.addWidget(self.linkageMethodComboBox, 4, 2, 1, 1)
        self.outputFieldNameLine = QtWidgets.QLineEdit(self.settingsGroup)
        self.outputFieldNameLine.setMaxLength(10)
        self.outputFieldNameLine.setObjectName("outputFieldNameLine")
        self.gridLayout.addWidget(self.outputFieldNameLine, 5, 2, 1, 1)
        self.clusteringMethodComboBox = QtWidgets.QComboBox(self.settingsGroup)
        self.clusteringMethodComboBox.setObjectName("clusteringMethodComboBox")
        self.clusteringMethodComboBox.addItem("")
        self.clusteringMethodComboBox.addItem("")
        self.clusteringMethodComboBox.addItem("")
        self.gridLayout.addWidget(self.clusteringMethodComboBox, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.settingsGroup)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.settingsGroup)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.numberOfClustersSpinBox = QtWidgets.QSpinBox(self.settingsGroup)
        self.numberOfClustersSpinBox.setMinimum(2)
        self.numberOfClustersSpinBox.setProperty("value", 4)
        self.numberOfClustersSpinBox.setObjectName("numberOfClustersSpinBox")
        self.gridLayout.addWidget(self.numberOfClustersSpinBox, 2, 2, 1, 1)
        self.clusteringThresholdLine = QtWidgets.QLineEdit(self.settingsGroup)
        self.clusteringThresholdLine.setObjectName("clusteringThresholdLine")
        self.gridLayout.addWidget(self.clusteringThresholdLine, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.settingsGroup)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.settingsGroup)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.settingsGroup)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.settingsGroup)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 6, 0, 1, 1)
        self.gridLayout_2.addWidget(self.settingsGroup, 5, 0, 1, 6)
        self.helpLink = QtWidgets.QLabel(AttributeBasedClusteringDialog)
        self.helpLink.setAlignment(QtCore.Qt.AlignCenter)
        self.helpLink.setOpenExternalLinks(True)
        self.helpLink.setObjectName("helpLink")
        self.gridLayout_2.addWidget(self.helpLink, 6, 3, 1, 1)
        self.fieldsTable = QtWidgets.QTableWidget(AttributeBasedClusteringDialog)
        self.fieldsTable.setObjectName("fieldsTable")
        self.fieldsTable.setColumnCount(2)
        self.fieldsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.fieldsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fieldsTable.setHorizontalHeaderItem(1, item)
        self.gridLayout_2.addWidget(self.fieldsTable, 0, 3, 5, 3)

        self.retranslateUi(AttributeBasedClusteringDialog)
        self.linkageMethodComboBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(AttributeBasedClusteringDialog)

    def retranslateUi(self, AttributeBasedClusteringDialog):
        _translate = QtCore.QCoreApplication.translate
        AttributeBasedClusteringDialog.setWindowTitle(_translate("AttributeBasedClusteringDialog", "Attribute based clustering"))
        self.label_2.setText(_translate("AttributeBasedClusteringDialog", "Fields:"))
        self.addFieldButton.setText(_translate("AttributeBasedClusteringDialog", "--->"))
        self.deleteAllButton.setText(_translate("AttributeBasedClusteringDialog", "Delete all"))
        self.deleteSelectedButton.setText(_translate("AttributeBasedClusteringDialog", "Delete selected"))
        self.runButton.setText(_translate("AttributeBasedClusteringDialog", "Run"))
        self.cancelButton.setText(_translate("AttributeBasedClusteringDialog", "Cancel"))
        self.label.setText(_translate("AttributeBasedClusteringDialog", "Vector layer:"))
        self.settingsGroup.setTitle(_translate("AttributeBasedClusteringDialog", "Settings"))
        self.linkageMethodComboBox.setItemText(0, _translate("AttributeBasedClusteringDialog", "single"))
        self.linkageMethodComboBox.setItemText(1, _translate("AttributeBasedClusteringDialog", "complete"))
        self.linkageMethodComboBox.setItemText(2, _translate("AttributeBasedClusteringDialog", "average"))
        self.linkageMethodComboBox.setItemText(3, _translate("AttributeBasedClusteringDialog", "median"))
        self.linkageMethodComboBox.setItemText(4, _translate("AttributeBasedClusteringDialog", "weighted"))
        self.linkageMethodComboBox.setItemText(5, _translate("AttributeBasedClusteringDialog", "ward"))
        self.outputFieldNameLine.setText(_translate("AttributeBasedClusteringDialog", "class"))
        self.clusteringMethodComboBox.setItemText(0, _translate("AttributeBasedClusteringDialog", "K-Means (not weighted, scipy required, fast, known number of clusters)"))
        self.clusteringMethodComboBox.setItemText(1, _translate("AttributeBasedClusteringDialog", "Hierarchical (weighted, native, slow, known number of clusters)"))
        self.clusteringMethodComboBox.setItemText(2, _translate("AttributeBasedClusteringDialog", "Hierarchical-2 (not weighted, scipy required, fast, auto number of clusters)"))
        self.label_4.setText(_translate("AttributeBasedClusteringDialog", "Number of clusters"))
        self.label_7.setText(_translate("AttributeBasedClusteringDialog", "Linkage method"))
        self.clusteringThresholdLine.setText(_translate("AttributeBasedClusteringDialog", "0.5"))
        self.label_3.setText(_translate("AttributeBasedClusteringDialog", "Clusteng method"))
        self.label_6.setText(_translate("AttributeBasedClusteringDialog", "Clustering threshold"))
        self.label_5.setText(_translate("AttributeBasedClusteringDialog", "Output field name"))
        self.checkBox.setText(_translate("AttributeBasedClusteringDialog", "Normalize attributes"))
        self.helpLink.setText(_translate("AttributeBasedClusteringDialog", "<a href=\"http://www.ekazakov.info/projects/abc_tutorial.html\">Help</a>"))
        item = self.fieldsTable.horizontalHeaderItem(0)
        item.setText(_translate("AttributeBasedClusteringDialog", "Field"))
        item = self.fieldsTable.horizontalHeaderItem(1)
        item.setText(_translate("AttributeBasedClusteringDialog", "Weight"))

from qgsfieldcombobox import QgsFieldComboBox
from qgsmaplayercombobox import QgsMapLayerComboBox
