# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attribute_based_clustering_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AttributeBasedClusteringDialog(object):
    def setupUi(self, AttributeBasedClusteringDialog):
        AttributeBasedClusteringDialog.setObjectName("AttributeBasedClusteringDialog")
        AttributeBasedClusteringDialog.resize(749, 656)
        self.gridLayout_2 = QtWidgets.QGridLayout(AttributeBasedClusteringDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.progressBar = QtWidgets.QProgressBar(AttributeBasedClusteringDialog)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 6, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(AttributeBasedClusteringDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.fieldsComboBox = QgsFieldComboBox(AttributeBasedClusteringDialog)
        self.fieldsComboBox.setObjectName("fieldsComboBox")
        self.gridLayout_2.addWidget(self.fieldsComboBox, 1, 1, 1, 2)
        self.addFieldButton = QtWidgets.QPushButton(AttributeBasedClusteringDialog)
        self.addFieldButton.setObjectName("addFieldButton")
        self.gridLayout_2.addWidget(self.addFieldButton, 2, 1, 1, 2)
        self.deleteSelectedButton = QtWidgets.QPushButton(AttributeBasedClusteringDialog)
        self.deleteSelectedButton.setObjectName("deleteSelectedButton")
        self.gridLayout_2.addWidget(self.deleteSelectedButton, 3, 1, 1, 2)
        self.vectorLayerComboBox = QgsMapLayerComboBox(AttributeBasedClusteringDialog)
        self.vectorLayerComboBox.setObjectName("vectorLayerComboBox")
        self.gridLayout_2.addWidget(self.vectorLayerComboBox, 0, 1, 1, 2)
        self.deleteAllButton = QtWidgets.QPushButton(AttributeBasedClusteringDialog)
        self.deleteAllButton.setObjectName("deleteAllButton")
        self.gridLayout_2.addWidget(self.deleteAllButton, 4, 1, 1, 2)
        self.runButton = QtWidgets.QPushButton(AttributeBasedClusteringDialog)
        self.runButton.setObjectName("runButton")
        self.gridLayout_2.addWidget(self.runButton, 6, 4, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(AttributeBasedClusteringDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout_2.addWidget(self.cancelButton, 6, 5, 1, 1)
        self.label = QtWidgets.QLabel(AttributeBasedClusteringDialog)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.fieldsTable = QtWidgets.QTableWidget(AttributeBasedClusteringDialog)
        self.fieldsTable.setObjectName("fieldsTable")
        self.fieldsTable.setColumnCount(2)
        self.fieldsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.fieldsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fieldsTable.setHorizontalHeaderItem(1, item)
        self.gridLayout_2.addWidget(self.fieldsTable, 0, 3, 5, 3)
        self.helpLink = QtWidgets.QLabel(AttributeBasedClusteringDialog)
        self.helpLink.setAlignment(QtCore.Qt.AlignCenter)
        self.helpLink.setOpenExternalLinks(True)
        self.helpLink.setObjectName("helpLink")
        self.gridLayout_2.addWidget(self.helpLink, 6, 3, 1, 1)
        self.settingsGroup = QtWidgets.QGroupBox(AttributeBasedClusteringDialog)
        self.settingsGroup.setObjectName("settingsGroup")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.settingsGroup)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.settingsGroup)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.kmeansThresholdLineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.kmeansThresholdLineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.kmeansThresholdLineEdit.setObjectName("kmeansThresholdLineEdit")
        self.gridLayout.addWidget(self.kmeansThresholdLineEdit, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.helpLink_2 = QtWidgets.QLabel(self.tab_3)
        self.helpLink_2.setAlignment(QtCore.Qt.AlignCenter)
        self.helpLink_2.setOpenExternalLinks(True)
        self.helpLink_2.setObjectName("helpLink_2")
        self.gridLayout.addWidget(self.helpLink_2, 0, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.kmeansIterSpinBox = QtWidgets.QSpinBox(self.tab_3)
        self.kmeansIterSpinBox.setMinimum(1)
        self.kmeansIterSpinBox.setMaximum(9999)
        self.kmeansIterSpinBox.setProperty("value", 20)
        self.kmeansIterSpinBox.setObjectName("kmeansIterSpinBox")
        self.gridLayout.addWidget(self.kmeansIterSpinBox, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.kmeans2MethodComboBox = QtWidgets.QComboBox(self.tab_5)
        self.kmeans2MethodComboBox.setObjectName("kmeans2MethodComboBox")
        self.kmeans2MethodComboBox.addItem("")
        self.kmeans2MethodComboBox.addItem("")
        self.gridLayout_3.addWidget(self.kmeans2MethodComboBox, 3, 1, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 0, 2, 1)
        self.helpLink_3 = QtWidgets.QLabel(self.tab_5)
        self.helpLink_3.setAlignment(QtCore.Qt.AlignCenter)
        self.helpLink_3.setOpenExternalLinks(True)
        self.helpLink_3.setObjectName("helpLink_3")
        self.gridLayout_3.addWidget(self.helpLink_3, 0, 0, 1, 3)
        self.label_12 = QtWidgets.QLabel(self.tab_5)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 4, 1, 1, 1)
        self.kmeans2IterSpinBox = QtWidgets.QSpinBox(self.tab_5)
        self.kmeans2IterSpinBox.setMinimum(1)
        self.kmeans2IterSpinBox.setMaximum(99999999)
        self.kmeans2IterSpinBox.setProperty("value", 20)
        self.kmeans2IterSpinBox.setObjectName("kmeans2IterSpinBox")
        self.gridLayout_3.addWidget(self.kmeans2IterSpinBox, 1, 1, 2, 2)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_18 = QtWidgets.QLabel(self.tab_6)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.linkageMethodComboBox = QtWidgets.QComboBox(self.tab_4)
        self.linkageMethodComboBox.setObjectName("linkageMethodComboBox")
        self.linkageMethodComboBox.addItem("")
        self.linkageMethodComboBox.addItem("")
        self.linkageMethodComboBox.addItem("")
        self.linkageMethodComboBox.addItem("")
        self.linkageMethodComboBox.addItem("")
        self.linkageMethodComboBox.addItem("")
        self.gridLayout_4.addWidget(self.linkageMethodComboBox, 6, 1, 1, 1)
        self.criterionComBox = QtWidgets.QComboBox(self.tab_4)
        self.criterionComBox.setObjectName("criterionComBox")
        self.criterionComBox.addItem("")
        self.criterionComBox.addItem("")
        self.criterionComBox.addItem("")
        self.gridLayout_4.addWidget(self.criterionComBox, 3, 1, 1, 1)
        self.clusteringThresholdLine = QtWidgets.QLineEdit(self.tab_4)
        self.clusteringThresholdLine.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.clusteringThresholdLine.setObjectName("clusteringThresholdLine")
        self.gridLayout_4.addWidget(self.clusteringThresholdLine, 1, 1, 1, 1)
        self.metricComboBox = QtWidgets.QComboBox(self.tab_4)
        self.metricComboBox.setObjectName("metricComboBox")
        self.metricComboBox.addItem("")
        self.metricComboBox.addItem("")
        self.metricComboBox.addItem("")
        self.metricComboBox.addItem("")
        self.metricComboBox.addItem("")
        self.metricComboBox.addItem("")
        self.metricComboBox.addItem("")
        self.metricComboBox.addItem("")
        self.metricComboBox.addItem("")
        self.metricComboBox.addItem("")
        self.metricComboBox.addItem("")
        self.metricComboBox.addItem("")
        self.metricComboBox.addItem("")
        self.metricComboBox.addItem("")
        self.metricComboBox.addItem("")
        self.metricComboBox.addItem("")
        self.metricComboBox.addItem("")
        self.metricComboBox.addItem("")
        self.metricComboBox.addItem("")
        self.metricComboBox.addItem("")
        self.gridLayout_4.addWidget(self.metricComboBox, 4, 1, 1, 1)
        self.maxNumberOfClustersSpinBox = QtWidgets.QSpinBox(self.tab_4)
        self.maxNumberOfClustersSpinBox.setObjectName("maxNumberOfClustersSpinBox")
        self.gridLayout_4.addWidget(self.maxNumberOfClustersSpinBox, 2, 1, 1, 1)
        self.depthSpinBox = QtWidgets.QSpinBox(self.tab_4)
        self.depthSpinBox.setMinimum(1)
        self.depthSpinBox.setProperty("value", 2)
        self.depthSpinBox.setObjectName("depthSpinBox")
        self.gridLayout_4.addWidget(self.depthSpinBox, 5, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_4)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.helpLink_4 = QtWidgets.QLabel(self.tab_4)
        self.helpLink_4.setAlignment(QtCore.Qt.AlignCenter)
        self.helpLink_4.setOpenExternalLinks(True)
        self.helpLink_4.setObjectName("helpLink_4")
        self.gridLayout_4.addWidget(self.helpLink_4, 0, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 7, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_6.addWidget(self.tabWidget, 6, 0, 1, 2)
        self.numberOfClustersSpinBox = QtWidgets.QSpinBox(self.settingsGroup)
        self.numberOfClustersSpinBox.setMinimum(2)
        self.numberOfClustersSpinBox.setProperty("value", 4)
        self.numberOfClustersSpinBox.setObjectName("numberOfClustersSpinBox")
        self.gridLayout_6.addWidget(self.numberOfClustersSpinBox, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.settingsGroup)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 1)
        self.outputFieldNameLine = QtWidgets.QLineEdit(self.settingsGroup)
        self.outputFieldNameLine.setMaxLength(10)
        self.outputFieldNameLine.setObjectName("outputFieldNameLine")
        self.gridLayout_6.addWidget(self.outputFieldNameLine, 4, 1, 1, 1)
        self.clusteringMethodComboBox = QtWidgets.QComboBox(self.settingsGroup)
        self.clusteringMethodComboBox.setObjectName("clusteringMethodComboBox")
        self.clusteringMethodComboBox.addItem("")
        self.clusteringMethodComboBox.addItem("")
        self.clusteringMethodComboBox.addItem("")
        self.clusteringMethodComboBox.addItem("")
        self.gridLayout_6.addWidget(self.clusteringMethodComboBox, 0, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.settingsGroup)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_6.addWidget(self.checkBox, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.settingsGroup)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.settingsGroup)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.settingsGroup)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 5, 0, 1, 1)
        self.gridLayout_2.addWidget(self.settingsGroup, 5, 0, 1, 6)

        self.retranslateUi(AttributeBasedClusteringDialog)
        self.tabWidget.setCurrentIndex(0)
        self.linkageMethodComboBox.setCurrentIndex(1)
        self.criterionComBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(AttributeBasedClusteringDialog)

    def retranslateUi(self, AttributeBasedClusteringDialog):
        _translate = QtCore.QCoreApplication.translate
        AttributeBasedClusteringDialog.setWindowTitle(_translate("AttributeBasedClusteringDialog", "Attribute based clustering"))
        self.label_2.setText(_translate("AttributeBasedClusteringDialog", "Fields:"))
        self.addFieldButton.setText(_translate("AttributeBasedClusteringDialog", "--->"))
        self.deleteSelectedButton.setText(_translate("AttributeBasedClusteringDialog", "Delete selected"))
        self.deleteAllButton.setText(_translate("AttributeBasedClusteringDialog", "Delete all"))
        self.runButton.setText(_translate("AttributeBasedClusteringDialog", "Run"))
        self.cancelButton.setText(_translate("AttributeBasedClusteringDialog", "Cancel"))
        self.label.setText(_translate("AttributeBasedClusteringDialog", "Vector layer:"))
        item = self.fieldsTable.horizontalHeaderItem(0)
        item.setText(_translate("AttributeBasedClusteringDialog", "Field"))
        item = self.fieldsTable.horizontalHeaderItem(1)
        item.setText(_translate("AttributeBasedClusteringDialog", "Weight"))
        self.helpLink.setText(_translate("AttributeBasedClusteringDialog", "<a href=\"http://www.ekazakov.info/projects/abc_tutorial.html\">Help</a>"))
        self.settingsGroup.setTitle(_translate("AttributeBasedClusteringDialog", "Settings"))
        self.kmeansThresholdLineEdit.setText(_translate("AttributeBasedClusteringDialog", "0.00001"))
        self.label_10.setText(_translate("AttributeBasedClusteringDialog", "Threshold"))
        self.helpLink_2.setText(_translate("AttributeBasedClusteringDialog", "<a href=\"https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.vq.kmeans.html#scipy.cluster.vq.kmeans\">Original documentation for algorithm</a>"))
        self.label_9.setText(_translate("AttributeBasedClusteringDialog", "Number of times\n"
"to run k-means"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("AttributeBasedClusteringDialog", "K-Means"))
        self.kmeans2MethodComboBox.setItemText(0, _translate("AttributeBasedClusteringDialog", "random"))
        self.kmeans2MethodComboBox.setItemText(1, _translate("AttributeBasedClusteringDialog", "points"))
        self.label_11.setText(_translate("AttributeBasedClusteringDialog", "Number of iterations\n"
"of the k-means\n"
"algorithm to run"))
        self.helpLink_3.setText(_translate("AttributeBasedClusteringDialog", "<a href=\"https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.vq.kmeans2.html#scipy.cluster.vq.kmeans2\">Original documentation for algorithm</a>"))
        self.label_12.setText(_translate("AttributeBasedClusteringDialog", "Method for\n"
"initialization"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("AttributeBasedClusteringDialog", "K-Means-2"))
        self.label_18.setText(_translate("AttributeBasedClusteringDialog", "Nothing to configure"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("AttributeBasedClusteringDialog", "Hierarchical"))
        self.linkageMethodComboBox.setItemText(0, _translate("AttributeBasedClusteringDialog", "single"))
        self.linkageMethodComboBox.setItemText(1, _translate("AttributeBasedClusteringDialog", "complete"))
        self.linkageMethodComboBox.setItemText(2, _translate("AttributeBasedClusteringDialog", "average"))
        self.linkageMethodComboBox.setItemText(3, _translate("AttributeBasedClusteringDialog", "median"))
        self.linkageMethodComboBox.setItemText(4, _translate("AttributeBasedClusteringDialog", "weighted"))
        self.linkageMethodComboBox.setItemText(5, _translate("AttributeBasedClusteringDialog", "ward"))
        self.criterionComBox.setItemText(0, _translate("AttributeBasedClusteringDialog", "inconsistent"))
        self.criterionComBox.setItemText(1, _translate("AttributeBasedClusteringDialog", "distance"))
        self.criterionComBox.setItemText(2, _translate("AttributeBasedClusteringDialog", "maxclust"))
        self.clusteringThresholdLine.setText(_translate("AttributeBasedClusteringDialog", "0.5"))
        self.metricComboBox.setItemText(0, _translate("AttributeBasedClusteringDialog", "euclidean"))
        self.metricComboBox.setItemText(1, _translate("AttributeBasedClusteringDialog", "minkowski"))
        self.metricComboBox.setItemText(2, _translate("AttributeBasedClusteringDialog", "cityblock"))
        self.metricComboBox.setItemText(3, _translate("AttributeBasedClusteringDialog", "seuclidean"))
        self.metricComboBox.setItemText(4, _translate("AttributeBasedClusteringDialog", "sqeuclidean"))
        self.metricComboBox.setItemText(5, _translate("AttributeBasedClusteringDialog", "cosine"))
        self.metricComboBox.setItemText(6, _translate("AttributeBasedClusteringDialog", "correlation"))
        self.metricComboBox.setItemText(7, _translate("AttributeBasedClusteringDialog", "hamming"))
        self.metricComboBox.setItemText(8, _translate("AttributeBasedClusteringDialog", "jaccard"))
        self.metricComboBox.setItemText(9, _translate("AttributeBasedClusteringDialog", "chebyshev"))
        self.metricComboBox.setItemText(10, _translate("AttributeBasedClusteringDialog", "canberra"))
        self.metricComboBox.setItemText(11, _translate("AttributeBasedClusteringDialog", "braycurtis"))
        self.metricComboBox.setItemText(12, _translate("AttributeBasedClusteringDialog", "mahalanobis"))
        self.metricComboBox.setItemText(13, _translate("AttributeBasedClusteringDialog", "matching"))
        self.metricComboBox.setItemText(14, _translate("AttributeBasedClusteringDialog", "dice"))
        self.metricComboBox.setItemText(15, _translate("AttributeBasedClusteringDialog", "kulsinski"))
        self.metricComboBox.setItemText(16, _translate("AttributeBasedClusteringDialog", "rogerstanimoto"))
        self.metricComboBox.setItemText(17, _translate("AttributeBasedClusteringDialog", "russellrao"))
        self.metricComboBox.setItemText(18, _translate("AttributeBasedClusteringDialog", "sokalmichener"))
        self.metricComboBox.setItemText(19, _translate("AttributeBasedClusteringDialog", "sokalsneath"))
        self.label_15.setText(_translate("AttributeBasedClusteringDialog", "Criterion"))
        self.label_14.setText(_translate("AttributeBasedClusteringDialog", "Max number of clusters"))
        self.label_17.setText(_translate("AttributeBasedClusteringDialog", "Metric"))
        self.label_7.setText(_translate("AttributeBasedClusteringDialog", "Linkage method"))
        self.label_16.setText(_translate("AttributeBasedClusteringDialog", "Depth"))
        self.label_6.setText(_translate("AttributeBasedClusteringDialog", "Clustering threshold"))
        self.helpLink_4.setText(_translate("AttributeBasedClusteringDialog", "<a href=\"https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.fclusterdata.html#scipy.cluster.hierarchy.fclusterdata\">Original documentation for algorithm</a>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("AttributeBasedClusteringDialog", "Hierarchical-2"))
        self.label_8.setText(_translate("AttributeBasedClusteringDialog", "Number of clusters"))
        self.outputFieldNameLine.setText(_translate("AttributeBasedClusteringDialog", "class"))
        self.clusteringMethodComboBox.setItemText(0, _translate("AttributeBasedClusteringDialog", "K-Means (not weighted, scipy required, fast, known number of clusters)"))
        self.clusteringMethodComboBox.setItemText(1, _translate("AttributeBasedClusteringDialog", "K-Means-2 (not weighted, scipy required, fast, known number of clusters)"))
        self.clusteringMethodComboBox.setItemText(2, _translate("AttributeBasedClusteringDialog", "Hierarchical (weighted, native, slow, known number of clusters)"))
        self.clusteringMethodComboBox.setItemText(3, _translate("AttributeBasedClusteringDialog", "Hierarchical-2 (not weighted, scipy required, fast, auto number of clusters)"))
        self.checkBox.setText(_translate("AttributeBasedClusteringDialog", "Normalize attributes"))
        self.label_5.setText(_translate("AttributeBasedClusteringDialog", "Output field name"))
        self.label_3.setText(_translate("AttributeBasedClusteringDialog", "Clusteng method"))
        self.label_13.setText(_translate("AttributeBasedClusteringDialog", "Additional options:"))

from qgsfieldcombobox import QgsFieldComboBox
from qgsmaplayercombobox import QgsMapLayerComboBox
